name:
  pop-epi
channels:
  - freenome
  - conda-forge
  - bioconda
  - default
dependencies:
  - bwa
  - methpipe
  - numpy
  - openblas
  - pandas
  - pheniqs
  - picard
  - samtools
  - snakemake
  - ucsc-bedgraphtobigwig
