import json

import pandas as pd

from utils import pheniqs

configfile: "config.yaml"

units = pd.read_csv(config["data"]["multiplex_units"], index_col="id")
samples = pd.read_csv(config["data"]["multiplex_samples"], index_col="SM")

rule _:
    input:
        expand(
            "{unit}_{output}", unit=units.index.values,
            output=[
                "inter.cram",
                "demux.cram",
                "demux_config.json",
                "demux_report.json"
            ]
        ),
        

include: "rules/pheniqs_interleave.smk"
include: "rules/pheniqs_demultiplex_config.smk"
include: "rules/pheniqs_demultiplex.smk"









